version: '3'
services:
  node:
    build: ./node
    image: bbox-node
    working_dir: /bbox
    volumes:
      - ./node:/bbox
  container-info:
    image: matuszeman/container-info
  container-info2:
    image: matuszeman/container-info
  mongo:
    image: mongo:3.6
