version: '3'
services:
  container-info:
    image: matuszeman/container-info
    extra_hosts:
      - 'container-info:172.17.0.1'
      - 'container-info.local.app.garden:172.17.0.1'
      - 'container-info2:172.17.0.1'
      - 'container-info2.local.app.garden:172.17.0.1'
      - 'mongo:172.17.0.1'
      - 'mongo.local.app.garden:172.17.0.1'
      - 'proxy-http:172.17.0.1'
      - 'http.proxy.local.app.garden:172.17.0.1'
      - 'proxy-https:172.17.0.1'
      - 'https.proxy.local.app.garden:172.17.0.1'
  container-info2:
    image: matuszeman/container-info
    extra_hosts:
      - 'container-info:172.17.0.1'
      - 'container-info.local.app.garden:172.17.0.1'
      - 'container-info2:172.17.0.1'
      - 'container-info2.local.app.garden:172.17.0.1'
      - 'mongo:172.17.0.1'
      - 'mongo.local.app.garden:172.17.0.1'
      - 'proxy-http:172.17.0.1'
      - 'http.proxy.local.app.garden:172.17.0.1'
      - 'proxy-https:172.17.0.1'
      - 'https.proxy.local.app.garden:172.17.0.1'
  mongo:
    image: 'mongo:3.6'
    volumes:
      - './mongo/.bbox/state/volumes/data:/data/db'
    extra_hosts:
      - 'container-info:172.17.0.1'
      - 'container-info.local.app.garden:172.17.0.1'
      - 'container-info2:172.17.0.1'
      - 'container-info2.local.app.garden:172.17.0.1'
      - 'mongo:172.17.0.1'
      - 'mongo.local.app.garden:172.17.0.1'
      - 'proxy-http:172.17.0.1'
      - 'http.proxy.local.app.garden:172.17.0.1'
      - 'proxy-https:172.17.0.1'
      - 'https.proxy.local.app.garden:172.17.0.1'
  node:
    image: bbox-node
    build:
      context: ./node
      dockerfile: Dockerfile
    working_dir: /bbox
    volumes:
      - './node:/bbox'
    extra_hosts:
      - 'container-info:172.17.0.1'
      - 'container-info.local.app.garden:172.17.0.1'
      - 'container-info2:172.17.0.1'
      - 'container-info2.local.app.garden:172.17.0.1'
      - 'mongo:172.17.0.1'
      - 'mongo.local.app.garden:172.17.0.1'
      - 'proxy-http:172.17.0.1'
      - 'http.proxy.local.app.garden:172.17.0.1'
      - 'proxy-https:172.17.0.1'
      - 'https.proxy.local.app.garden:172.17.0.1'
